#!/usr/bin/env bash
# Phase 0 step 10 — Pre-exec verification probes per PLAN_V5.md.
# All probes run from CLI project root. KEY=VALUE output appended to docs/SDK_NOTES.md.

set -eo pipefail
trap 'rm -rf smoke-test' EXIT

# Initialize SDK_NOTES.md fresh.
mkdir -p docs
cat > docs/SDK_NOTES.md <<'HEADER'
# SDK probe notes (Phase 0 step 10)

Generated by `scripts/run-probes.sh`. KEY=VALUE lines below; CLI runtime greps `^<key>=`.

HEADER

# Probe -1 — detect PM. Single shared PM var across all later probes.
if yarn --version >/dev/null 2>&1; then PM=yarn; else PM=npm; fi
echo "SMOKE_PM=$PM" >> docs/SDK_NOTES.md

# Probe 0 — create smoke target (no install).
echo "==> Probe 0: scaffold smoke-test"
npx --yes create-expo-app smoke-test --template blank-typescript --no-install

# Probe 0b — single install pass populates node_modules.
echo "==> Probe 0b: install babel-preset-expo (auto-syncs all template deps)"
if [ "$PM" = "yarn" ]; then
  ( cd smoke-test && yarn add --dev babel-preset-expo )
else
  ( cd smoke-test && npm install --save-dev babel-preset-expo )
fi

# Probe 1 — target Expo SDK.
echo "==> Probe 1: EXPO_SDK_VERSION"
echo "EXPO_SDK_VERSION=$(jq -r '.dependencies.expo' smoke-test/package.json)" \
  >> docs/SDK_NOTES.md

# Probe 2 — auto-inclusion of worklets/reanimated plugin.
echo "==> Probe 2: BABEL_PRESET_AUTO_INCLUDES_WORKLETS"
AUTO=0
if find smoke-test/node_modules/babel-preset-expo -name "*.js" -print0 2>/dev/null \
   | xargs -0 grep -lqE "react-native-(worklets|reanimated)/plugin" 2>/dev/null; then
  AUTO=1
else
  TRANSITIVE=$(jq -r \
    '.dependencies."react-native-worklets" // .dependencies."react-native-reanimated" // empty' \
    smoke-test/node_modules/babel-preset-expo/package.json 2>/dev/null)
  if [ -n "$TRANSITIVE" ]; then AUTO=1; fi
fi
echo "BABEL_PRESET_AUTO_INCLUDES_WORKLETS=$AUTO" >> docs/SDK_NOTES.md

# Probe 3 — worklets package name (capture stderr to log).
echo "==> Probe 3: WORKLETS_PKG"
WORKLETS_LOG=docs/SDK_NOTES_probe3-stderr.log
: > "$WORKLETS_LOG"
if ( cd smoke-test && npx expo install react-native-worklets ) >/dev/null 2>>"$WORKLETS_LOG"; then
  echo "WORKLETS_PKG=react-native-worklets" >> docs/SDK_NOTES.md
elif ( cd smoke-test && npx expo install react-native-worklets-core ) >/dev/null 2>>"$WORKLETS_LOG"; then
  echo "WORKLETS_PKG=react-native-worklets-core" >> docs/SDK_NOTES.md
else
  echo "WORKLETS_PKG=UNKNOWN" >> docs/SDK_NOTES.md
  echo "# Probe 3 failure details: see $WORKLETS_LOG" >> docs/SDK_NOTES.md
fi

# Probe 4 — baseUrl in expo/tsconfig.base.
echo "==> Probe 4: EXPO_TSCONFIG_BASEURL"
BASEURL=$(jq -r '.compilerOptions.baseUrl // "null"' \
  smoke-test/node_modules/expo/tsconfig.base.json)
echo "EXPO_TSCONFIG_BASEURL=$BASEURL" >> docs/SDK_NOTES.md

# Probe 5 — expo install PM-flag support.
echo "==> Probe 5: FLAGS_OK"
if ( cd smoke-test && npx --yes expo install --help 2>&1 ) | grep -qE "(--yarn|--npm)"; then
  FLAGS_OK=1
else
  FLAGS_OK=0
fi
echo "FLAGS_OK=$FLAGS_OK" >> docs/SDK_NOTES.md

# Probe 6 — expo install --check idempotency on populated node_modules.
echo "==> Probe 6: EXPO_CHECK_IDEMPOTENT_OK"
if ( cd smoke-test && npx expo install --check >/dev/null 2>&1 ); then
  echo "EXPO_CHECK_IDEMPOTENT_OK=1" >> docs/SDK_NOTES.md
else
  echo "EXPO_CHECK_IDEMPOTENT_OK=0" >> docs/SDK_NOTES.md
fi

# Probe 7 — lockfile materialization. Branches on FLAGS_OK + PM.
echo "==> Probe 7: PROBE_PASS"
(
  cd smoke-test
  rm -f yarn.lock package-lock.json
  if [ "$FLAGS_OK" = "1" ]; then
    if [ "$PM" = "yarn" ]; then
      npx --yes expo install expo-router --yarn >/dev/null 2>&1 || true
    else
      npx --yes expo install expo-router --npm >/dev/null 2>&1 || true
    fi
  else
    if [ "$PM" = "yarn" ]; then
      : > yarn.lock
    else
      echo '{"name":"smoke-test","version":"1.0.0","lockfileVersion":3,"requires":true,"packages":{}}' > package-lock.json
    fi
    npx --yes expo install expo-router >/dev/null 2>&1 || true
  fi
  if [ "$PM" = "yarn" ] && [ -f yarn.lock ]; then
    echo "PROBE_PASS=1"
  elif [ "$PM" = "npm" ] && [ -f package-lock.json ]; then
    echo "PROBE_PASS=1"
  else
    echo "PROBE_PASS=0"
  fi
) >> docs/SDK_NOTES.md

# Probe 8 — Branch B npm-lockfile seed (only when FLAGS_OK=0 AND PM=npm).
if [ "$FLAGS_OK" = "0" ] && [ "$PM" = "npm" ]; then
  echo "==> Probe 8: NPM_SEED_OK"
  (
    cd smoke-test
    rm -f yarn.lock package-lock.json
    echo '{"name":"smoke-test","version":"1.0.0","lockfileVersion":3,"requires":true,"packages":{}}' \
      > package-lock.json
    npx --yes expo install expo-router >/dev/null 2>&1 || true
    if [ -f package-lock.json ]; then
      echo "NPM_SEED_OK=1"
    else
      echo "NPM_SEED_OK=0"
    fi
  ) >> docs/SDK_NOTES.md
fi

echo "==> All probes complete. SDK_NOTES.md:"
cat docs/SDK_NOTES.md
