// Phase 6 generators. Sentinel + marker-block emission for _layout.tsx,
// and full enum file generation for src/ui/theme/fonts.ts.
//
// Decision-locked (rev 3): fonts type is plain `export enum Fonts` (NOT
// `const enum`). See spec Decision #7.

import type { Answers } from "./prompts.js";
import type { InstalledFamily } from "./fontsInstaller.js";

const MARKER_START = "// codingpixel:fonts-start";
const MARKER_END = "// codingpixel:fonts-end";

/** Uppercase + replace whitespace with underscore for enum key prefix. */
function familyPrefix(displayName: string): string {
  return displayName.trim().toUpperCase().replace(/\s+/g, "_");
}

/**
 * Build the full contents of `src/ui/theme/fonts.ts`. Caller writes to disk.
 * Throws if `secondary` is non-null but `primary` is null (P3 defensive —
 * should be unreachable via gathering layer).
 */
export function generateFontsEnumFile(
  primary: InstalledFamily | null,
  secondary: InstalledFamily | null,
): string {
  if (!primary && secondary) {
    throw new Error("generateFontsEnumFile: primary cannot be null when secondary is set.");
  }
  if (!primary) {
    return [
      "// Generated by react-native-expo-boilerplate — no font family selected.",
      "export enum Fonts {}",
      "",
    ].join("\n");
  }
  const lines: string[] = [];
  lines.push("// Generated by react-native-expo-boilerplate.");
  lines.push(
    `// Primary: ${primary.displayName} (${primary.variants.length} variants) — keys: ${primary.variants
      .map((v) => v.enumKey)
      .join(", ")}.`,
  );
  if (secondary) {
    lines.push(
      `// Secondary: ${secondary.displayName} (${secondary.variants.length} variants) — keys prefixed ${familyPrefix(
        secondary.displayName,
      )}_.`,
    );
  }
  lines.push("// Re-run `react-native-expo-boilerplate add fonts` to change.");
  lines.push("export enum Fonts {");
  for (const v of primary.variants) {
    lines.push(`  ${v.enumKey} = "${primary.fileBase}${v.suffix}",`);
  }
  if (secondary) {
    const prefix = familyPrefix(secondary.displayName);
    for (const v of secondary.variants) {
      lines.push(`  ${prefix}_${v.enumKey} = "${secondary.fileBase}${v.suffix}",`);
    }
  }
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

/**
 * Build the marker-wrapped block body for _layout.tsx:
 *   useFonts hook + (optional) useEffect for SplashScreen.hideAsync + guards.
 * Returns the body INSIDE the markers (caller wraps with `// codingpixel:fonts-start`
 * and `// codingpixel:fonts-end`). Returns empty string when primary is null.
 */
export function buildMarkerBlockBody(
  primary: InstalledFamily | null,
  secondary: InstalledFamily | null,
  hasSplashScreen: boolean,
): string {
  if (!primary) return "";
  const pairs: Array<[string, string]> = [];
  for (const v of primary.variants) {
    pairs.push([`${primary.fileBase}${v.suffix}`, `${primary.fileBase}${v.suffix}.ttf`]);
  }
  if (secondary) {
    for (const v of secondary.variants) {
      pairs.push([`${secondary.fileBase}${v.suffix}`, `${secondary.fileBase}${v.suffix}.ttf`]);
    }
  }
  const mapEntries = pairs
    .map(([key, file]) => `    "${key}": require("../assets/fonts/${file}"),`)
    .join("\n");
  const lines: string[] = [];
  lines.push(`  const [fontsLoaded, fontError] = useFonts({\n${mapEntries}\n  });`);
  if (hasSplashScreen) {
    lines.push(`  useEffect(() => {`);
    lines.push(`    if (fontsLoaded || fontError) {`);
    lines.push(`      SplashScreen.hideAsync();`);
    lines.push(`    }`);
    lines.push(`  }, [fontsLoaded, fontError]);`);
  }
  lines.push(`  if (fontError) throw fontError;`);
  lines.push(`  if (!fontsLoaded) return null;`);
  return lines.join("\n");
}

/**
 * Build the three pieces inserted into `_layout.tsx` sentinels:
 *   - import line(s) for useFonts (+ useEffect if hasSplashScreen)
 *   - marker-wrapped block body (hook + optional useEffect + guards)
 *   - empty guard string (guard now lives inside the marker block)
 *
 * Empty `primary` → all three return empty strings → sentinel lines drop.
 */
export function generateUseFontsBlocks(
  primary: InstalledFamily | null,
  secondary: InstalledFamily | null,
  hasSplashScreen: boolean,
): { importBlock: string; hookBlock: string; guardBlock: string } {
  if (!primary) {
    return { importBlock: "", hookBlock: "", guardBlock: "" };
  }
  const importLines: string[] = [`import { useFonts } from "expo-font";`];
  if (hasSplashScreen) importLines.push(`import { useEffect } from "react";`);
  const importBlock = importLines.join("\n");
  const body = buildMarkerBlockBody(primary, secondary, hasSplashScreen);
  const hookBlock = `  ${MARKER_START}\n${body}\n  ${MARKER_END}`;
  return { importBlock, hookBlock, guardBlock: "" };
}

/**
 * Build the bottom-sheet provider sentinel triple.
 *
 * `bottomSheet === false` → all three empty → sentinel lines drop.
 */
export function generateBottomSheetProviderBlocks(
  bottomSheet: boolean,
): { importBlock: string; openBlock: string; closeBlock: string } {
  if (!bottomSheet) {
    return { importBlock: "", openBlock: "", closeBlock: "" };
  }
  return {
    importBlock: `import { BottomSheetModalProvider } from "@gorhom/bottom-sheet";`,
    openBlock: `                <BottomSheetModalProvider>`,
    closeBlock: `                </BottomSheetModalProvider>`,
  };
}

/**
 * Convenience: build the full sentinel-replacement map for `patchLayout`.
 * Caller passes resolved InstalledFamilys + hasSplashScreen explicitly so
 * the generator stays pure.
 */
export function buildLayoutReplacements(
  answers: Answers,
  primary: InstalledFamily | null,
  secondary: InstalledFamily | null,
  hasSplashScreen: boolean,
): Record<string, string> {
  const fonts = generateUseFontsBlocks(primary, secondary, hasSplashScreen);
  const bs = generateBottomSheetProviderBlocks(answers.bottomSheet);
  return {
    USE_FONTS_IMPORT: fonts.importBlock,
    USE_FONTS_HOOK: fonts.hookBlock,
    USE_FONTS_GUARD: fonts.guardBlock,
    BOTTOM_SHEET_PROVIDER_IMPORT: bs.importBlock,
    BOTTOM_SHEET_PROVIDER_OPEN: bs.openBlock,
    BOTTOM_SHEET_PROVIDER_CLOSE: bs.closeBlock,
  };
}
